/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DayCard {
    'day': Date;
    'disable': boolean;
    'locale': string;
    'selected': boolean;
  }
  interface WeekCalendar {
    'blockBefore': boolean;
    'disableDates': string;
    'disableWeekends': boolean;
    'enableDates': string;
    'locale': string;
    'selectedDay': any;
    'startDate': any;
    'startDay': number;
  }
}

declare namespace LocalJSX {
  interface DayCard extends JSXBase.HTMLAttributes {
    'day'?: Date;
    'disable'?: boolean;
    'locale'?: string;
    'selected'?: boolean;
  }
  interface WeekCalendar extends JSXBase.HTMLAttributes {
    'blockBefore'?: boolean;
    'disableDates'?: string;
    'disableWeekends'?: boolean;
    'enableDates'?: string;
    'locale'?: string;
    'onValueUpdated'?: (event: CustomEvent<any>) => void;
    'selectedDay'?: any;
    'startDate'?: any;
    'startDay'?: number;
  }

  interface IntrinsicElements {
    'day-card': DayCard;
    'week-calendar': WeekCalendar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLDayCardElement extends Components.DayCard, HTMLStencilElement {}
  var HTMLDayCardElement: {
    prototype: HTMLDayCardElement;
    new (): HTMLDayCardElement;
  };

  interface HTMLWeekCalendarElement extends Components.WeekCalendar, HTMLStencilElement {}
  var HTMLWeekCalendarElement: {
    prototype: HTMLWeekCalendarElement;
    new (): HTMLWeekCalendarElement;
  };

  interface HTMLElementTagNameMap {
    'day-card': HTMLDayCardElement;
    'week-calendar': HTMLWeekCalendarElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

